### ISSUE TITLE
notify中on_play事件的建议

### ISSUE THREAD

**Issue by zywu31** [pingostack/pingos#10]
测试发现 如果on_play 配置url访问不了，服务器就自动放行了。
建议加个属性来决定这种情况是否自动放行。

**Comment by im-pingo** [comment]
已经解决
`ignore_invalid_notify off;`
可以满足你的需求。

**Comment by im-pingo** [comment]
> 测试发现 如果on_play 配置url访问不了，服务器就自动放行了。
> 建议加个属性来决定这种情况是否自动放行。

已经解决
ignore_invalid_notify off;
可以满足你的需求。
