### ISSUE TITLE
control 指令操作不了

### ISSUE THREAD

**Issue by mainidear** [pingostack/pingos#13]
![1](https://user-images.githubusercontent.com/5800685/82751314-e5b46600-9de8-11ea-9329-ceefe349dbd3.png)
192.168.83.200 是pingos 服务器
192.168.83.1 是vlc播放器

我播放器还能继续播放呢？怎么回事？
我也操作了停止录播这些操作，也不行。请作者忙里抽空，回答一下哈

**Comment by im-pingo** [comment]
> ![1](https://user-images.githubusercontent.com/5800685/82751314-e5b46600-9de8-11ea-9329-ceefe349dbd3.png)
> 192.168.83.200 是pingos 服务器
> 192.168.83.1 是vlc播放器
> 
> 我播放器还能继续播放呢？怎么回事？
> 我也操作了停止录播这些操作，也不行。请作者忙里抽空，回答一下哈

截图里你是要对client操作，所以必须要有cliendid参数，如果不使用clientid参数，请把drop/client替换成drop/publisher 或者drop/subscriber

![image](https://user-images.githubusercontent.com/8231000/82751401-7ee37c80-9de9-11ea-8471-efe462ff0960.png)
