### ISSUE TITLE
rename m3u8failed

### ISSUE THREAD

**Issue by lystormenvoy** [pingostack/pingos#14]
error.log show log like this
````
2020/05/25 15:19:06 [error] 3176#0: *65 hls: rename failed: '/usr/local/nginx/html/app/ly.m3u8.bak'->'/usr/local/nginx/html/app/ly.m3u8' (2: No such file or directory), client: unix:/tmp/rtmp.3, server: 0.0.0.0:1935, session: 0000000003B70710, stream: default/hls/ly
2020/05/25 15:20:02 [error] 3177#0: *281 hls: rename failed: '/usr/local/nginx/html/app/ly.m3u8.bak'->'/usr/local/nginx/html/app/ly.m3u8' (2: No such file or directory), client: unix:/tmp/rtmp.3, server: 0.0.0.0:1935, session: 0000000003B70710, stream: default/hls/ly
````
3176 and 3177 are different process id of nginx worker.

**Comment by im-pingo** [comment]
> error.log show log like this
> 
> ```
> 2020/05/25 15:19:06 [error] 3176#0: *65 hls: rename failed: '/usr/local/nginx/html/app/ly.m3u8.bak'->'/usr/local/nginx/html/app/ly.m3u8' (2: No such file or directory), client: unix:/tmp/rtmp.3, server: 0.0.0.0:1935, session: 0000000003B70710, stream: default/hls/ly
> 2020/05/25 15:20:02 [error] 3177#0: *281 hls: rename failed: '/usr/local/nginx/html/app/ly.m3u8.bak'->'/usr/local/nginx/html/app/ly.m3u8' (2: No such file or directory), client: unix:/tmp/rtmp.3, server: 0.0.0.0:1935, session: 0000000003B70710, stream: default/hls/ly
> ```
> 
> 3176 and 3177 are different process id of nginx worker.

Show your nginx.conf
