### ISSUE TITLE
服务core dump

### ISSUE THREAD

**Issue by steven-tianx** [pingostack/pingos#28]
hi httpflv的拉流过程中，随机出现服务进程异常重启（core dump）
core日志如下：
![image](https://user-images.githubusercontent.com/69305525/89605213-9803b180-d89f-11ea-80f5-0e8bf2d0740f.png)
![image](https://user-images.githubusercontent.com/69305525/89605251-ac47ae80-d89f-11ea-8900-395133955d11.png)
![image](https://user-images.githubusercontent.com/69305525/89605247-a81b9100-d89f-11ea-8c35-d39df866e9ff.png)
nginx日志如下：
2020/08/06 10:48:52 [info] 33167#0: *93823 http flv live, client timed out (110: Connection timed out), client: 10.200.20.62, server: , request: "GET /live/b34f586544924ab8a9a9f66f4761672d HTTP/1.0", host: "live2.pptv.com"
2020/08/06 10:48:52 [info] 33167#0: *93823 http flv live, cleanup, client: 10.200.20.62, server: , request: "GET /live/b34f586544924ab8a9a9f66f4761672d HTTP/1.0", host: "live2.pptv.com"
2020/08/06 10:48:52 [info] 33167#0: *93823 finalize fake session, server: 0.0.0.0:1935, session: 000000000245A680, stream: pptv/live/b34f586544924ab8a9a9f66f4761672d, client: 10.200.20.62, server: , request: "GET /live/b34f586544924ab8a9a9f66f4761672d HTTP/1.0", host: "live2.pptv.com"
2020/08/06 10:48:52 [info] 33167#0: *93823 disconnect, server: 0.0.0.0:1935, session: 000000000245A680, stream: pptv/live/b34f586544924ab8a9a9f66f4761672d, client: 10.200.20.62, server: , request: "GET /live/b34f586544924ab8a9a9f66f4761672d HTTP/1.0", host: "live2.pptv.com"
2020/08/06 10:48:52 [info] 33167#0: *93823 rtmp close stream filter, server: 0.0.0.0:1935, session: 000000000245A680, stream: pptv/live/b34f586544924ab8a9a9f66f4761672d, client: 10.200.20.62, server: , request: "GET /live/b34f586544924ab8a9a9f66f4761672d HTTP/1.0", host: "live2.pptv.com"
2020/08/06 10:48:52 [info] 33167#0: *93823 finalize session, server: 0.0.0.0:1935, session: 000000000245A680, stream: pptv/live/b34f586544924ab8a9a9f66f4761672d, client: 10.200.20.62, server: , request: "GET /live/b34f586544924ab8a9a9f66f4761672d HTTP/1.0", host: "live2.pptv.com"
2020/08/06 10:48:52 [info] 33167#0: *93823 asyn finalize http request, server: 0.0.0.0:1935, session: 000000000245A680, stream: pptv/live/b34f586544924ab8a9a9f66f4761672d, client: 10.200.20.62, server: 0.0.0.0:80
2020/08/06 10:48:52 [notice] 32285#0: signal 17 (SIGCHLD) received from 33167
2020/08/06 10:48:52 [alert] 32285#0: worker process 33167 exited on signal 11 (core dumped)

**Comment by im-pingo** [comment]
> hi httpflv的拉流过程中，随机出现服务进程异常重启（core dump）
> core日志如下：
> ![image](https://user-images.githubusercontent.com/69305525/89605213-9803b180-d89f-11ea-80f5-0e8bf2d0740f.png)
> ![image](https://user-images.githubusercontent.com/69305525/89605251-ac47ae80-d89f-11ea-8900-395133955d11.png)
> ![image](https://user-images.githubusercontent.com/69305525/89605247-a81b9100-d89f-11ea-8c35-d39df866e9ff.png)
> nginx日志如下：
> 2020/08/06 10:48:52 [info] 33167#0: *93823 http flv live, client timed out (110: Connection timed out), client: 10.200.20.62, server: , request: "GET /live/b34f586544924ab8a9a9f66f4761672d HTTP/1.0", host: "live2.pptv.com"
> 2020/08/06 10:48:52 [info] 33167#0: *93823 http flv live, cleanup, client: 10.200.20.62, server: , request: "GET /live/b34f586544924ab8a9a9f66f4761672d HTTP/1.0", host: "live2.pptv.com"
> 2020/08/06 10:48:52 [info] 33167#0: *93823 finalize fake session, server: 0.0.0.0:1935, session: 000000000245A680, stream: pptv/live/b34f586544924ab8a9a9f66f4761672d, client: 10.200.20.62, server: , request: "GET /live/b34f586544924ab8a9a9f66f4761672d HTTP/1.0", host: "live2.pptv.com"
> 2020/08/06 10:48:52 [info] 33167#0: *93823 disconnect, server: 0.0.0.0:1935, session: 000000000245A680, stream: pptv/live/b34f586544924ab8a9a9f66f4761672d, client: 10.200.20.62, server: , request: "GET /live/b34f586544924ab8a9a9f66f4761672d HTTP/1.0", host: "live2.pptv.com"
> 2020/08/06 10:48:52 [info] 33167#0: *93823 rtmp close stream filter, server: 0.0.0.0:1935, session: 000000000245A680, stream: pptv/live/b34f586544924ab8a9a9f66f4761672d, client: 10.200.20.62, server: , request: "GET /live/b34f586544924ab8a9a9f66f4761672d HTTP/1.0", host: "live2.pptv.com"
> 2020/08/06 10:48:52 [info] 33167#0: *93823 finalize session, server: 0.0.0.0:1935, session: 000000000245A680, stream: pptv/live/b34f586544924ab8a9a9f66f4761672d, client: 10.200.20.62, server: , request: "GET /live/b34f586544924ab8a9a9f66f4761672d HTTP/1.0", host: "live2.pptv.com"
> 2020/08/06 10:48:52 [info] 33167#0: *93823 asyn finalize http request, server: 0.0.0.0:1935, session: 000000000245A680, stream: pptv/live/b34f586544924ab8a9a9f66f4761672d, client: 10.200.20.62, server: 0.0.0.0:80
> 2020/08/06 10:48:52 [notice] 32285#0: signal 17 (SIGCHLD) received from 33167
> 2020/08/06 10:48:52 [alert] 32285#0: worker process 33167 exited on signal 11 (core dumped)

http-flv客户端超时后重复触发finalize session导致服务crash，现已修复。
