### ISSUE TITLE
关于点播功能(VOD)

### ISSUE THREAD

**Issue by xuteng935** [pingostack/pingos#31]
你好，我想使用点播功能，在nginx.conf里面做了如下配置，但是提示出错，'play'关键字未识别，烦请看看点播功能如何激活。

> rmtp{
>     ...
>     server {
>         ...
>         application vod {
>            play /home/Videos;
>         }
>     }
> }

执行./sbin/nginx -t ， 提示如下：
nginx: [emerg] unknown directive "play" in /usr/local/pingos/conf/nginx.conf:53
nginx: configuration file /usr/local/pingos/conf/nginx.conf test failed

**Comment by im-pingo** [comment]
> 你好，我想使用点播功能，在nginx.conf里面做了如下配置，但是提示出错，'play'关键字未识别，烦请看看点播功能如何激活。
> 
> > rmtp{
> > ...
> > server {
> > ...
> > application vod {
> > play /home/Videos;
> > }
> > }
> > }
> 
> 执行./sbin/nginx -t ， 提示如下：
> nginx: [emerg] unknown directive "play" in /usr/local/pingos/conf/nginx.conf:53
> nginx: configuration file /usr/local/pingos/conf/nginx.conf test failed

你好，pingos没有支持rtmp点播，你可以将录像文件简单处理成mp4、hls，使用http点播。
