### ISSUE TITLE
error log 重覆出現相同的訊息mpegts vps_copy 1, sps_copy 1, pps_copy 1

### ISSUE THREAD

**Issue by sonny420** [pingostack/pingos#36]
您好，請問一下rtmp 推流上去後，毎個流都會一直重覆出現以下log 
2020/11/03 15:38:02 [error] 306641#0: *149 mpegts vps_copy 1, sps_copy 1, pps_copy 1
, client: 127.0.0.1, server: 0.0.0.0:1935, session: 00000000039B5530, stream: 000/live/xxxxxxx

這個是正常的log 還是我用ffmpeg 推流錯誤呢？

**Comment by im-pingo** [comment]
> 您好，請問一下rtmp 推流上去後，毎個流都會一直重覆出現以下log
> 2020/11/03 15:38:02 [error] 306641#0: *149 mpegts vps_copy 1, sps_copy 1, pps_copy 1
> , client: 127.0.0.1, server: 0.0.0.0:1935, session: 00000000039B5530, stream: 000/live/xxxxxxx
> 
> 這個是正常的log 還是我用ffmpeg 推流錯誤呢？

你好， mpegts vps_copy 1, sps_copy 1, pps_copy 1 , client: 127.0.0.1, server: 0.0.0.0:1935, session: 00000000039B5530, stream: 000/live/xxxxxxx
这条错误日志的日志级别应该是debug，是我失误将这条log的日志级别设置成了error，所以忽略它或者在源码里注释掉这条输出即可。
