### ISSUE TITLE
hls h265 错误

### ISSUE THREAD

**Issue by yingchengpa** [pingostack/pingos#38]
我使用提供的金山ffmpeg 补丁，发送h265码流时，ffmpeg会出现错误，提示
error writing trailer of rtmp://127.0.0.1:1938/live/2 : connection reset by peer .
于是查看了pingos中logs/ 下的error日志：
hls： failed to read 22 byte .....
hls:   error appending vps/sps/pps nals ;

于是我手动关闭了 hls的支持， hls  off ， 然后ffmpeg 可以转发h265的流了

**Comment by sonny420** [comment]
> 我使用提供的金山ffmpeg 补丁，发送h265码流时，ffmpeg会出现错误，提示
> error writing trailer of rtmp://127.0.0.1:1938/live/2 : connection reset by peer .
> 于是查看了pingos中logs/ 下的error日志：
> hls： failed to read 22 byte .....
> hls: error appending vps/sps/pps nals ;
> 
> 于是我手动关闭了 hls的支持， hls off ， 然后ffmpeg 可以转发h265的流了

我使用 ffmpeg +hevc 3.2 / 3.4 / 4 的版本推h265 沒有出現hls 錯誤，但會一直重覆出現以下訊息
2020/11/03 15:38:02 [error] 306641#0: *149 mpegts vps_copy 1, sps_copy 1, pps_copy 1
, client: 127.0.0.1, server: 0.0.0.0:1935, session: 00000000039B5530, stream: 000/live/xxxxxxx

我用的來源是mpeg-ts 流透過ffmpeg 轉發rtmp 流，來源mpeg-ts 就是hevc編碼了，所以我猜是mpeg-ts 解析有問題吧，你的部份我猜也是來源切片有問題?

**Comment by im-pingo** [comment]
> > 我使用提供的金山ffmpeg 补丁，发送h265码流时，ffmpeg会出现错误，提示
> > error writing trailer of rtmp://127.0.0.1:1938/live/2 : connection reset by peer .
> > 于是查看了pingos中logs/ 下的error日志：
> > hls： failed to read 22 byte .....
> > hls: error appending vps/sps/pps nals ;
> > 于是我手动关闭了 hls的支持， hls off ， 然后ffmpeg 可以转发h265的流了
> 
> 我使用 ffmpeg +hevc 3.2 / 3.4 / 4 的版本推h265 沒有出現hls 錯誤，但會一直重覆出現以下訊息
> 2020/11/03 15:38:02 [error] 306641#0: *149 mpegts vps_copy 1, sps_copy 1, pps_copy 1
> , client: 127.0.0.1, server: 0.0.0.0:1935, session: 00000000039B5530, stream: 000/live/xxxxxxx
> 
> 我用的來源是mpeg-ts 流透過ffmpeg 轉發rtmp 流，來源mpeg-ts 就是hevc編碼了，所以我猜是mpeg-ts 解析有問題吧，你的部份我猜也是來源切片有問題?

你好， mpegts vps_copy 1, sps_copy 1, pps_copy 1 , client: 127.0.0.1, server: 0.0.0.0:1935, session: 00000000039B5530, stream: 000/live/xxxxxxx
这条错误日志的日志级别应该是debug，是我失误将这条log的日志级别设置成了error。
h265编码经过验证是可以正常工作的。
@yingchengpa 需要检查一下h265编码的vps sps和pps是否正常。

**Comment by yingchengpa** [comment]
好的 ，多谢！ 我使用的是rtsp转发到rtmp，有些公司的rtsp中缺失pps等信息，使用ffmpeg -i rtsp://204.204.70.67:554/video2 -vcodec copy -an -f hevc - | ffmpeg -f hevc -i - -c copy -f flv rtmp://127.0.0.1:1938/live/2
 这个命令解决
