### ISSUE TITLE
默认安装后，本地使用ffmpeg 推流 返回 Connection to tcp://127.0.0.1:1935 failed: Connection refused

### ISSUE THREAD

**Issue by ROYduan** [pingostack/pingos#53]
在mac 电脑中的linux虚拟机安装后    mac浏览器访问：http://127.0.0.1 可以正常返回 welcome to nginx！
但是在mac 上本地使用ffmpeg 推流时 返回 connection refused
ffmpeg -re -i work_space/videos/720p_2000_src1.mp4 -vcodec copy -acodec copy -f flv rtmp://127.0.0.1:1935/live/test1

**Comment by lystormenvoy** [comment]
说不定只是忘了放开1935端口

**Comment by ROYduan** [comment]
真是这个原因，虚拟机忘记开放1935 这个端口了
